CREATE TABLE public.clientes (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    empresa_id uuid,
    razon_social text NOT NULL,
    nombre_fantasia text,
    cuit text,
    condicion_iva text DEFAULT 'consumidor_final'::text,
    domicilio text,
    localidad text,
    zona_id uuid,
    telefono text,
    email text,
    lista_precio_id uuid,
    limite_credito numeric(12,2) DEFAULT 0,
    dias_credito integer DEFAULT 0,
    activo boolean DEFAULT true,
    notas text,
    created_at timestamp with time zone DEFAULT now(),
    score_actual integer,
    score_categoria text,
    lat numeric(10,7),
    lng numeric(10,7),
    score_actualizado timestamp with time zone,
    direccion text GENERATED ALWAYS AS (domicilio) STORED,
    saldo_deuda numeric(12,2) DEFAULT 0,
    usuario_id uuid,
    bloqueado boolean DEFAULT false,
    bloqueado_motivo text,
    saldo_cuenta_corriente numeric(12,2) DEFAULT 0
);
