CREATE TABLE public.alertas_score (
CREATE TABLE public.alertas_stock (
CREATE TABLE public.audit_log (
CREATE TABLE public.bloqueos_cliente (
CREATE TABLE public.canjes_recompensas (
CREATE TABLE public.categorias (
CREATE TABLE public.cheques (
CREATE TABLE public.ciclos_compra (
CREATE TABLE public.clientes (
CREATE TABLE public.cobros (
CREATE TABLE public.contadores_empresa (
CREATE TABLE public.cta_cte (
CREATE TABLE public.depositos (
CREATE TABLE public.dispositivos_push (
CREATE TABLE public.empresas (
CREATE TABLE public.entregas (
CREATE TABLE public.facturas (
CREATE TABLE public.integraciones_pago (
CREATE TABLE public.listas_precios (
CREATE TABLE public.lotes (
CREATE TABLE public.movimientos_cta_cte (
CREATE TABLE public.movimientos_puntos (
CREATE TABLE public.movimientos_stock (
CREATE TABLE public.notas_internas (
CREATE TABLE public.notif_log (
CREATE TABLE public.notificaciones_push (
CREATE TABLE public.ordenes_compra (
CREATE TABLE public.ordenes_compra_items (
CREATE TABLE public.pedido_items (
CREATE TABLE public.pedidos (
CREATE TABLE public.precios_items (
CREATE TABLE public.presupuesto_items (
CREATE TABLE public.presupuestos (
CREATE TABLE public.productos (
CREATE TABLE public.programas_fidelizacion (
CREATE TABLE public.saldo_puntos (
CREATE TABLE public.recompensas (
CREATE TABLE public.reglas_score (
CREATE TABLE public.rutas (
CREATE TABLE public.scores_cliente (
CREATE TABLE public.stock (
CREATE TABLE public.sugerencias_pedido (
CREATE TABLE public.transacciones_pago (
CREATE TABLE public.usuarios (
CREATE TABLE public.zonas (
