CREATE TABLE auth.audit_log_entries (
CREATE TABLE auth.custom_oauth_providers (
CREATE TABLE auth.flow_state (
CREATE TABLE auth.identities (
CREATE TABLE auth.instances (
CREATE TABLE auth.mfa_amr_claims (
CREATE TABLE auth.mfa_challenges (
CREATE TABLE auth.mfa_factors (
CREATE TABLE auth.oauth_authorizations (
CREATE TABLE auth.oauth_client_states (
CREATE TABLE auth.oauth_clients (
CREATE TABLE auth.oauth_consents (
CREATE TABLE auth.one_time_tokens (
CREATE TABLE auth.refresh_tokens (
CREATE TABLE auth.saml_providers (
CREATE TABLE auth.saml_relay_states (
CREATE TABLE auth.schema_migrations (
CREATE TABLE auth.sessions (
CREATE TABLE auth.sso_domains (
CREATE TABLE auth.sso_providers (
CREATE TABLE auth.users (
CREATE TABLE auth.webauthn_challenges (
CREATE TABLE auth.webauthn_credentials (
CREATE TABLE public.alertas_score (
CREATE TABLE public.alertas_stock (
CREATE TABLE public.audit_log (
CREATE TABLE public.bloqueos_cliente (
CREATE TABLE public.canjes_recompensas (
CREATE TABLE public.categorias (
CREATE TABLE public.cheques (
CREATE TABLE public.ciclos_compra (
CREATE TABLE public.clientes (
CREATE TABLE public.cobros (
CREATE TABLE public.contadores_empresa (
CREATE TABLE public.cta_cte (
CREATE TABLE public.depositos (
CREATE TABLE public.dispositivos_push (
CREATE TABLE public.empresas (
CREATE TABLE public.entregas (
CREATE TABLE public.facturas (
CREATE TABLE public.integraciones_pago (
CREATE TABLE public.listas_precios (
CREATE TABLE public.lotes (
CREATE TABLE public.movimientos_cta_cte (
CREATE TABLE public.movimientos_puntos (
CREATE TABLE public.movimientos_stock (
CREATE TABLE public.notas_internas (
CREATE TABLE public.notif_log (
CREATE TABLE public.notificaciones_push (
CREATE TABLE public.ordenes_compra (
CREATE TABLE public.ordenes_compra_items (
CREATE TABLE public.pedido_items (
CREATE TABLE public.pedidos (
CREATE TABLE public.precios_items (
CREATE TABLE public.presupuesto_items (
CREATE TABLE public.presupuestos (
CREATE TABLE public.productos (
CREATE TABLE public.programas_fidelizacion (
CREATE TABLE public.saldo_puntos (
CREATE TABLE public.recompensas (
CREATE TABLE public.reglas_score (
CREATE TABLE public.rutas (
CREATE TABLE public.scores_cliente (
CREATE TABLE public.stock (
CREATE TABLE public.sugerencias_pedido (
CREATE TABLE public.transacciones_pago (
CREATE TABLE public.usuarios (
CREATE TABLE public.zonas (
CREATE TABLE realtime.messages (
CREATE TABLE realtime.messages_2026_06_13 (
CREATE TABLE realtime.messages_2026_06_14 (
CREATE TABLE realtime.messages_2026_06_15 (
CREATE TABLE realtime.messages_2026_06_16 (
CREATE TABLE realtime.messages_2026_06_17 (
CREATE TABLE realtime.messages_2026_06_18 (
CREATE TABLE realtime.messages_2026_06_19 (
CREATE TABLE realtime.schema_migrations (
CREATE TABLE realtime.subscription (
CREATE TABLE storage.buckets (
CREATE TABLE storage.buckets_analytics (
CREATE TABLE storage.buckets_vectors (
CREATE TABLE storage.migrations (
CREATE TABLE storage.objects (
CREATE TABLE storage.s3_multipart_uploads (
CREATE TABLE storage.s3_multipart_uploads_parts (
CREATE TABLE storage.vector_indexes (
